/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ReporterDashboardRouteImport } from './routes/reporter-dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as NewsNewsIdRouteImport } from './routes/news/$newsId'
import { Route as CategorySlugRouteImport } from './routes/category/$slug'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminReportersRouteImport } from './routes/admin/reporters'
import { Route as AdminProfileRouteImport } from './routes/admin/profile'
import { Route as AdminCategoryRouteImport } from './routes/admin/category'
import { Route as AdminNewsIndexRouteImport } from './routes/admin/news/index'
import { Route as AdminBlogIndexRouteImport } from './routes/admin/blog/index'
import { Route as AdminNewsCreateRouteImport } from './routes/admin/news/create'
import { Route as AdminBlogTagsRouteImport } from './routes/admin/blog/tags'
import { Route as AdminBlogCategoryRouteImport } from './routes/admin/blog/category'
import { Route as AdminNewsNewsIdEditRouteImport } from './routes/admin/news/$newsId.edit'
import { Route as AdminNewsNewsIdCommentsRouteImport } from './routes/admin/news/$newsId.comments'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ReporterDashboardRoute = ReporterDashboardRouteImport.update({
  id: '/reporter-dashboard',
  path: '/reporter-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const NewsNewsIdRoute = NewsNewsIdRouteImport.update({
  id: '/news/$newsId',
  path: '/news/$newsId',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReportersRoute = AdminReportersRouteImport.update({
  id: '/reporters',
  path: '/reporters',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategoryRoute = AdminCategoryRouteImport.update({
  id: '/category',
  path: '/category',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNewsIndexRoute = AdminNewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBlogIndexRoute = AdminBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNewsCreateRoute = AdminNewsCreateRouteImport.update({
  id: '/news/create',
  path: '/news/create',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBlogTagsRoute = AdminBlogTagsRouteImport.update({
  id: '/blog/tags',
  path: '/blog/tags',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBlogCategoryRoute = AdminBlogCategoryRouteImport.update({
  id: '/blog/category',
  path: '/blog/category',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNewsNewsIdEditRoute = AdminNewsNewsIdEditRouteImport.update({
  id: '/news/$newsId/edit',
  path: '/news/$newsId/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNewsNewsIdCommentsRoute = AdminNewsNewsIdCommentsRouteImport.update({
  id: '/news/$newsId/comments',
  path: '/news/$newsId/comments',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/reporter-dashboard': typeof ReporterDashboardRoute
  '/signup': typeof SignupRoute
  '/admin/category': typeof AdminCategoryRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reporters': typeof AdminReportersRoute
  '/admin/users': typeof AdminUsersRoute
  '/category/$slug': typeof CategorySlugRoute
  '/news/$newsId': typeof NewsNewsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/blog/category': typeof AdminBlogCategoryRoute
  '/admin/blog/tags': typeof AdminBlogTagsRoute
  '/admin/news/create': typeof AdminNewsCreateRoute
  '/admin/blog': typeof AdminBlogIndexRoute
  '/admin/news': typeof AdminNewsIndexRoute
  '/admin/news/$newsId/comments': typeof AdminNewsNewsIdCommentsRoute
  '/admin/news/$newsId/edit': typeof AdminNewsNewsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/reporter-dashboard': typeof ReporterDashboardRoute
  '/signup': typeof SignupRoute
  '/admin/category': typeof AdminCategoryRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reporters': typeof AdminReportersRoute
  '/admin/users': typeof AdminUsersRoute
  '/category/$slug': typeof CategorySlugRoute
  '/news/$newsId': typeof NewsNewsIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/blog/category': typeof AdminBlogCategoryRoute
  '/admin/blog/tags': typeof AdminBlogTagsRoute
  '/admin/news/create': typeof AdminNewsCreateRoute
  '/admin/blog': typeof AdminBlogIndexRoute
  '/admin/news': typeof AdminNewsIndexRoute
  '/admin/news/$newsId/comments': typeof AdminNewsNewsIdCommentsRoute
  '/admin/news/$newsId/edit': typeof AdminNewsNewsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/reporter-dashboard': typeof ReporterDashboardRoute
  '/signup': typeof SignupRoute
  '/admin/category': typeof AdminCategoryRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reporters': typeof AdminReportersRoute
  '/admin/users': typeof AdminUsersRoute
  '/category/$slug': typeof CategorySlugRoute
  '/news/$newsId': typeof NewsNewsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/blog/category': typeof AdminBlogCategoryRoute
  '/admin/blog/tags': typeof AdminBlogTagsRoute
  '/admin/news/create': typeof AdminNewsCreateRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/news/': typeof AdminNewsIndexRoute
  '/admin/news/$newsId/comments': typeof AdminNewsNewsIdCommentsRoute
  '/admin/news/$newsId/edit': typeof AdminNewsNewsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/dashboard'
    | '/login'
    | '/reporter-dashboard'
    | '/signup'
    | '/admin/category'
    | '/admin/profile'
    | '/admin/reporters'
    | '/admin/users'
    | '/category/$slug'
    | '/news/$newsId'
    | '/admin/'
    | '/admin/blog/category'
    | '/admin/blog/tags'
    | '/admin/news/create'
    | '/admin/blog'
    | '/admin/news'
    | '/admin/news/$newsId/comments'
    | '/admin/news/$newsId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard'
    | '/login'
    | '/reporter-dashboard'
    | '/signup'
    | '/admin/category'
    | '/admin/profile'
    | '/admin/reporters'
    | '/admin/users'
    | '/category/$slug'
    | '/news/$newsId'
    | '/admin'
    | '/admin/blog/category'
    | '/admin/blog/tags'
    | '/admin/news/create'
    | '/admin/blog'
    | '/admin/news'
    | '/admin/news/$newsId/comments'
    | '/admin/news/$newsId/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/about'
    | '/dashboard'
    | '/login'
    | '/reporter-dashboard'
    | '/signup'
    | '/admin/category'
    | '/admin/profile'
    | '/admin/reporters'
    | '/admin/users'
    | '/category/$slug'
    | '/news/$newsId'
    | '/admin/'
    | '/admin/blog/category'
    | '/admin/blog/tags'
    | '/admin/news/create'
    | '/admin/blog/'
    | '/admin/news/'
    | '/admin/news/$newsId/comments'
    | '/admin/news/$newsId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ReporterDashboardRoute: typeof ReporterDashboardRoute
  SignupRoute: typeof SignupRoute
  CategorySlugRoute: typeof CategorySlugRoute
  NewsNewsIdRoute: typeof NewsNewsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reporter-dashboard': {
      id: '/reporter-dashboard'
      path: '/reporter-dashboard'
      fullPath: '/reporter-dashboard'
      preLoaderRoute: typeof ReporterDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/news/$newsId': {
      id: '/news/$newsId'
      path: '/news/$newsId'
      fullPath: '/news/$newsId'
      preLoaderRoute: typeof NewsNewsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reporters': {
      id: '/admin/reporters'
      path: '/reporters'
      fullPath: '/admin/reporters'
      preLoaderRoute: typeof AdminReportersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/category': {
      id: '/admin/category'
      path: '/category'
      fullPath: '/admin/category'
      preLoaderRoute: typeof AdminCategoryRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/news/': {
      id: '/admin/news/'
      path: '/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AdminNewsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/blog/': {
      id: '/admin/blog/'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/news/create': {
      id: '/admin/news/create'
      path: '/news/create'
      fullPath: '/admin/news/create'
      preLoaderRoute: typeof AdminNewsCreateRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/blog/tags': {
      id: '/admin/blog/tags'
      path: '/blog/tags'
      fullPath: '/admin/blog/tags'
      preLoaderRoute: typeof AdminBlogTagsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/blog/category': {
      id: '/admin/blog/category'
      path: '/blog/category'
      fullPath: '/admin/blog/category'
      preLoaderRoute: typeof AdminBlogCategoryRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/news/$newsId/edit': {
      id: '/admin/news/$newsId/edit'
      path: '/news/$newsId/edit'
      fullPath: '/admin/news/$newsId/edit'
      preLoaderRoute: typeof AdminNewsNewsIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/news/$newsId/comments': {
      id: '/admin/news/$newsId/comments'
      path: '/news/$newsId/comments'
      fullPath: '/admin/news/$newsId/comments'
      preLoaderRoute: typeof AdminNewsNewsIdCommentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminCategoryRoute: typeof AdminCategoryRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminReportersRoute: typeof AdminReportersRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBlogCategoryRoute: typeof AdminBlogCategoryRoute
  AdminBlogTagsRoute: typeof AdminBlogTagsRoute
  AdminNewsCreateRoute: typeof AdminNewsCreateRoute
  AdminBlogIndexRoute: typeof AdminBlogIndexRoute
  AdminNewsIndexRoute: typeof AdminNewsIndexRoute
  AdminNewsNewsIdCommentsRoute: typeof AdminNewsNewsIdCommentsRoute
  AdminNewsNewsIdEditRoute: typeof AdminNewsNewsIdEditRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminCategoryRoute: AdminCategoryRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminReportersRoute: AdminReportersRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminBlogCategoryRoute: AdminBlogCategoryRoute,
  AdminBlogTagsRoute: AdminBlogTagsRoute,
  AdminNewsCreateRoute: AdminNewsCreateRoute,
  AdminBlogIndexRoute: AdminBlogIndexRoute,
  AdminNewsIndexRoute: AdminNewsIndexRoute,
  AdminNewsNewsIdCommentsRoute: AdminNewsNewsIdCommentsRoute,
  AdminNewsNewsIdEditRoute: AdminNewsNewsIdEditRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ReporterDashboardRoute: ReporterDashboardRoute,
  SignupRoute: SignupRoute,
  CategorySlugRoute: CategorySlugRoute,
  NewsNewsIdRoute: NewsNewsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
